### ISSUE TITLE
API keys in repo

### ISSUE THREAD

**Issue by gaieges** [sahil-gpm/flutter_bloc_news_app#1]
Not sure if you intended for this but just wanted to let you know as they still work:

https://github.com/sahilchavan94/flutter_bloc_news_app/blob/e01ab810b326e9fe9ce677a0f2beb090f8bc70a8/lib/home/repo/get_india_headlines_repo.dart#L12

**Comment by sahilchavan94** [comment]
Thanks for pointing out the issue, I removed the api key's. They were pushed by mistake

**Comment by gaieges** [comment]
You should trash the API keys too, they still work

**Comment by sahilchavan94** [comment]
Yeah will do it. Thanks for pointing out those issues
